/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.swetavk.avro;  
@SuppressWarnings("all")
/** Represents an Employee at a company */
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"com.swetavk.avro\",\"doc\":\"Represents an Employee at a company\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\",\"doc\":\"The persons given name\"},{\"name\":\"nickName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"AdditionalField\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"age\",\"type\":\"int\",\"default\":-1},{\"name\":\"emails\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"phoneNumber\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"PhoneNumber\",\"fields\":[{\"name\":\"areaCode\",\"type\":\"string\"},{\"name\":\"countryCode\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"prefix\",\"type\":\"string\"},{\"name\":\"number\",\"type\":\"string\"}]}]},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"Status\",\"symbols\":[\"RETIRED\",\"SALARY\",\"HOURLY\",\"PART_TIME\"]},\"default\":\"SALARY\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The persons given name */
  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence nickName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence AdditionalField;
  @Deprecated public int age;
  @Deprecated public java.util.List<java.lang.CharSequence> emails;
  @Deprecated public com.swetavk.avro.PhoneNumber phoneNumber;
  @Deprecated public com.swetavk.avro.Status status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Employee() {}

  /**
   * All-args constructor.
   */
  public Employee(java.lang.CharSequence firstName, java.lang.CharSequence nickName, java.lang.CharSequence lastName, java.lang.CharSequence AdditionalField, java.lang.Integer age, java.util.List<java.lang.CharSequence> emails, com.swetavk.avro.PhoneNumber phoneNumber, com.swetavk.avro.Status status) {
    this.firstName = firstName;
    this.nickName = nickName;
    this.lastName = lastName;
    this.AdditionalField = AdditionalField;
    this.age = age;
    this.emails = emails;
    this.phoneNumber = phoneNumber;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return nickName;
    case 2: return lastName;
    case 3: return AdditionalField;
    case 4: return age;
    case 5: return emails;
    case 6: return phoneNumber;
    case 7: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: nickName = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: AdditionalField = (java.lang.CharSequence)value$; break;
    case 4: age = (java.lang.Integer)value$; break;
    case 5: emails = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: phoneNumber = (com.swetavk.avro.PhoneNumber)value$; break;
    case 7: status = (com.swetavk.avro.Status)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * The persons given name   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * The persons given name   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'nickName' field.
   */
  public java.lang.CharSequence getNickName() {
    return nickName;
  }

  /**
   * Sets the value of the 'nickName' field.
   * @param value the value to set.
   */
  public void setNickName(java.lang.CharSequence value) {
    this.nickName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'AdditionalField' field.
   */
  public java.lang.CharSequence getAdditionalField() {
    return AdditionalField;
  }

  /**
   * Sets the value of the 'AdditionalField' field.
   * @param value the value to set.
   */
  public void setAdditionalField(java.lang.CharSequence value) {
    this.AdditionalField = value;
  }

  /**
   * Gets the value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'emails' field.
   */
  public java.util.List<java.lang.CharSequence> getEmails() {
    return emails;
  }

  /**
   * Sets the value of the 'emails' field.
   * @param value the value to set.
   */
  public void setEmails(java.util.List<java.lang.CharSequence> value) {
    this.emails = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   */
  public com.swetavk.avro.PhoneNumber getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(com.swetavk.avro.PhoneNumber value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public com.swetavk.avro.Status getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.swetavk.avro.Status value) {
    this.status = value;
  }

  /** Creates a new Employee RecordBuilder */
  public static com.swetavk.avro.Employee.Builder newBuilder() {
    return new com.swetavk.avro.Employee.Builder();
  }
  
  /** Creates a new Employee RecordBuilder by copying an existing Builder */
  public static com.swetavk.avro.Employee.Builder newBuilder(com.swetavk.avro.Employee.Builder other) {
    return new com.swetavk.avro.Employee.Builder(other);
  }
  
  /** Creates a new Employee RecordBuilder by copying an existing Employee instance */
  public static com.swetavk.avro.Employee.Builder newBuilder(com.swetavk.avro.Employee other) {
    return new com.swetavk.avro.Employee.Builder(other);
  }
  
  /**
   * RecordBuilder for Employee instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private java.lang.CharSequence firstName;
    private java.lang.CharSequence nickName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence AdditionalField;
    private int age;
    private java.util.List<java.lang.CharSequence> emails;
    private com.swetavk.avro.PhoneNumber phoneNumber;
    private com.swetavk.avro.Status status;

    /** Creates a new Builder */
    private Builder() {
      super(com.swetavk.avro.Employee.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.swetavk.avro.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nickName)) {
        this.nickName = data().deepCopy(fields()[1].schema(), other.nickName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.AdditionalField)) {
        this.AdditionalField = data().deepCopy(fields()[3].schema(), other.AdditionalField);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.age)) {
        this.age = data().deepCopy(fields()[4].schema(), other.age);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.emails)) {
        this.emails = data().deepCopy(fields()[5].schema(), other.emails);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[6].schema(), other.phoneNumber);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Employee instance */
    private Builder(com.swetavk.avro.Employee other) {
            super(com.swetavk.avro.Employee.SCHEMA$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nickName)) {
        this.nickName = data().deepCopy(fields()[1].schema(), other.nickName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.AdditionalField)) {
        this.AdditionalField = data().deepCopy(fields()[3].schema(), other.AdditionalField);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.age)) {
        this.age = data().deepCopy(fields()[4].schema(), other.age);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.emails)) {
        this.emails = data().deepCopy(fields()[5].schema(), other.emails);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[6].schema(), other.phoneNumber);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'firstName' field */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }
    
    /** Sets the value of the 'firstName' field */
    public com.swetavk.avro.Employee.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'firstName' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'firstName' field */
    public com.swetavk.avro.Employee.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'nickName' field */
    public java.lang.CharSequence getNickName() {
      return nickName;
    }
    
    /** Sets the value of the 'nickName' field */
    public com.swetavk.avro.Employee.Builder setNickName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nickName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'nickName' field has been set */
    public boolean hasNickName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'nickName' field */
    public com.swetavk.avro.Employee.Builder clearNickName() {
      nickName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'lastName' field */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }
    
    /** Sets the value of the 'lastName' field */
    public com.swetavk.avro.Employee.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'lastName' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'lastName' field */
    public com.swetavk.avro.Employee.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'AdditionalField' field */
    public java.lang.CharSequence getAdditionalField() {
      return AdditionalField;
    }
    
    /** Sets the value of the 'AdditionalField' field */
    public com.swetavk.avro.Employee.Builder setAdditionalField(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.AdditionalField = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'AdditionalField' field has been set */
    public boolean hasAdditionalField() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'AdditionalField' field */
    public com.swetavk.avro.Employee.Builder clearAdditionalField() {
      AdditionalField = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'age' field */
    public java.lang.Integer getAge() {
      return age;
    }
    
    /** Sets the value of the 'age' field */
    public com.swetavk.avro.Employee.Builder setAge(int value) {
      validate(fields()[4], value);
      this.age = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'age' field has been set */
    public boolean hasAge() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'age' field */
    public com.swetavk.avro.Employee.Builder clearAge() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'emails' field */
    public java.util.List<java.lang.CharSequence> getEmails() {
      return emails;
    }
    
    /** Sets the value of the 'emails' field */
    public com.swetavk.avro.Employee.Builder setEmails(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.emails = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'emails' field has been set */
    public boolean hasEmails() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'emails' field */
    public com.swetavk.avro.Employee.Builder clearEmails() {
      emails = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'phoneNumber' field */
    public com.swetavk.avro.PhoneNumber getPhoneNumber() {
      return phoneNumber;
    }
    
    /** Sets the value of the 'phoneNumber' field */
    public com.swetavk.avro.Employee.Builder setPhoneNumber(com.swetavk.avro.PhoneNumber value) {
      validate(fields()[6], value);
      this.phoneNumber = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'phoneNumber' field has been set */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'phoneNumber' field */
    public com.swetavk.avro.Employee.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public com.swetavk.avro.Status getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.swetavk.avro.Employee.Builder setStatus(com.swetavk.avro.Status value) {
      validate(fields()[7], value);
      this.status = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'status' field */
    public com.swetavk.avro.Employee.Builder clearStatus() {
      status = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public Employee build() {
      try {
        Employee record = new Employee();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nickName = fieldSetFlags()[1] ? this.nickName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.AdditionalField = fieldSetFlags()[3] ? this.AdditionalField : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.age = fieldSetFlags()[4] ? this.age : (java.lang.Integer) defaultValue(fields()[4]);
        record.emails = fieldSetFlags()[5] ? this.emails : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.phoneNumber = fieldSetFlags()[6] ? this.phoneNumber : (com.swetavk.avro.PhoneNumber) defaultValue(fields()[6]);
        record.status = fieldSetFlags()[7] ? this.status : (com.swetavk.avro.Status) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
